# listen address
listen = "0.0.0.0:6666"

[log]
# log level 1 = debug 2 = info 7 = slient
level = 1
file = ""
quotafile = "/usr/local/etc/wicklight/usage.txt"

[tls]
# certificate and private key file
certificate = ""
privatekey = ""

[fallback]
# fallback url, backend http server or apple.com et.al
target = "http://127.0.0.1:80"
# probe-host
host = "pr.example.org"
# white list
whitelist = ["github.com"]

# pac url = probe-host +  pacpath
pacpath = "/pac"
# pac file
pacfile = "build/https.pac"
pachost = "127.0.0.1"
pacport = "6666"

[[users]]
# username
username = "user1" 
# password
password = "password2"

[[users]]
username = "user2"
password = "password2"

[acl]
WhiteListMode = false
AllowLocal = false
HostsList = []
PortsList = []

